# Generated by Django 4.0.3 on 2022-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_inactive',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
