# Generated by Django 4.0.3 on 2022-04-26 08:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_is_inactive'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
